baseURL = 'https://example.org/'
languageCode = 'en-US'
title = '4rm0Byte'
theme = "github.com/nunocoracao/blowfish/v2"

[outputFormats.config]
mediaType = "application/yaml"
baseName = "config"
extension = "yml"
isPlainText = true
notAlternative = true
