disabled = false
locale = "en"
label = "English"
weight = 1
title = "4rm0Byte"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/Logo.png"
description = "My personal blog about technology, programming, and more."
# secondaryLogo = "img/Logo-alt.png"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Armoghan-ul-Mohmin"
email = "armoghanirshad06@gmail.com"
image = "img/armoghan.png"
imageQuality = 96
headline = "Digital Forensics & Cyber Security Graduate | Linux Power User | Blogger | Open Source Contributor"
bio = "Im a passionate tech enthusiast, dedicated to exploring the realms of technology, programming, and digital innovation. Through my blog, I aim to share insights, tutorials, and experiences that inspire and empower fellow tech enthusiasts. Join me on this journey as we unravel the fascinating world of technology together."
links = [
  { email = "mailto:armoghan@proton.me" },
  { discord = "https://discord.com/users/905072957141946399" },
  { facebook = "https://www.facebook.com/armoghanul.mohmin" },
  { github = "https://github.com/Armoghan-ul-Mohmin" },
  { gitlab = "https://gitlab.com/Armoghan-ul-Mohmin" },
  { instagram = "https://www.instagram.com/___armoghan/" },
  { linkedin = "http://www.linkedin.com/in/armoghan-ul-mohmin-4289a9248" },
  { twitter = "https://twitter.com/Armoghan12" }
]
